// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: message.proto

package x64

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type X64FPXReg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Significand []uint32 `protobuf:"varint,1,rep,packed,name=significand,proto3" json:"significand,omitempty"`
	Exponent    uint32   `protobuf:"varint,2,opt,name=exponent,proto3" json:"exponent,omitempty"`
	Reserved    []uint32 `protobuf:"varint,3,rep,packed,name=reserved,proto3" json:"reserved,omitempty"`
}

func (x *X64FPXReg) Reset() {
	*x = X64FPXReg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *X64FPXReg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X64FPXReg) ProtoMessage() {}

func (x *X64FPXReg) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X64FPXReg.ProtoReflect.Descriptor instead.
func (*X64FPXReg) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *X64FPXReg) GetSignificand() []uint32 {
	if x != nil {
		return x.Significand
	}
	return nil
}

func (x *X64FPXReg) GetExponent() uint32 {
	if x != nil {
		return x.Exponent
	}
	return 0
}

func (x *X64FPXReg) GetReserved() []uint32 {
	if x != nil {
		return x.Reserved
	}
	return nil
}

type X64XMMReg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element []uint32 `protobuf:"varint,1,rep,packed,name=element,proto3" json:"element,omitempty"`
}

func (x *X64XMMReg) Reset() {
	*x = X64XMMReg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *X64XMMReg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X64XMMReg) ProtoMessage() {}

func (x *X64XMMReg) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X64XMMReg.ProtoReflect.Descriptor instead.
func (*X64XMMReg) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *X64XMMReg) GetElement() []uint32 {
	if x != nil {
		return x.Element
	}
	return nil
}

type X64FPRegs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cwd      uint32       `protobuf:"varint,1,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Swd      uint32       `protobuf:"varint,2,opt,name=swd,proto3" json:"swd,omitempty"`
	Ftw      uint32       `protobuf:"varint,3,opt,name=ftw,proto3" json:"ftw,omitempty"`
	Fop      uint32       `protobuf:"varint,4,opt,name=fop,proto3" json:"fop,omitempty"`
	Rip      uint64       `protobuf:"varint,5,opt,name=rip,proto3" json:"rip,omitempty"`
	Rdp      uint64       `protobuf:"varint,6,opt,name=rdp,proto3" json:"rdp,omitempty"`
	Mxcsr    uint32       `protobuf:"varint,7,opt,name=mxcsr,proto3" json:"mxcsr,omitempty"`
	MxcrMask uint32       `protobuf:"varint,8,opt,name=mxcr_mask,json=mxcrMask,proto3" json:"mxcr_mask,omitempty"`
	St       []*X64FPXReg `protobuf:"bytes,9,rep,name=st,proto3" json:"st,omitempty"`
	Xmm      []*X64XMMReg `protobuf:"bytes,10,rep,name=xmm,proto3" json:"xmm,omitempty"`
	Reserved []uint32     `protobuf:"varint,11,rep,packed,name=reserved,proto3" json:"reserved,omitempty"`
}

func (x *X64FPRegs) Reset() {
	*x = X64FPRegs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *X64FPRegs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X64FPRegs) ProtoMessage() {}

func (x *X64FPRegs) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X64FPRegs.ProtoReflect.Descriptor instead.
func (*X64FPRegs) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *X64FPRegs) GetCwd() uint32 {
	if x != nil {
		return x.Cwd
	}
	return 0
}

func (x *X64FPRegs) GetSwd() uint32 {
	if x != nil {
		return x.Swd
	}
	return 0
}

func (x *X64FPRegs) GetFtw() uint32 {
	if x != nil {
		return x.Ftw
	}
	return 0
}

func (x *X64FPRegs) GetFop() uint32 {
	if x != nil {
		return x.Fop
	}
	return 0
}

func (x *X64FPRegs) GetRip() uint64 {
	if x != nil {
		return x.Rip
	}
	return 0
}

func (x *X64FPRegs) GetRdp() uint64 {
	if x != nil {
		return x.Rdp
	}
	return 0
}

func (x *X64FPRegs) GetMxcsr() uint32 {
	if x != nil {
		return x.Mxcsr
	}
	return 0
}

func (x *X64FPRegs) GetMxcrMask() uint32 {
	if x != nil {
		return x.MxcrMask
	}
	return 0
}

func (x *X64FPRegs) GetSt() []*X64FPXReg {
	if x != nil {
		return x.St
	}
	return nil
}

func (x *X64FPRegs) GetXmm() []*X64XMMReg {
	if x != nil {
		return x.Xmm
	}
	return nil
}

func (x *X64FPRegs) GetReserved() []uint32 {
	if x != nil {
		return x.Reserved
	}
	return nil
}

type CPUState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gregs  []uint64   `protobuf:"varint,1,rep,packed,name=gregs,proto3" json:"gregs,omitempty"`
	Fpregs *X64FPRegs `protobuf:"bytes,2,opt,name=fpregs,proto3" json:"fpregs,omitempty"`
}

func (x *CPUState) Reset() {
	*x = CPUState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CPUState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUState) ProtoMessage() {}

func (x *CPUState) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUState.ProtoReflect.Descriptor instead.
func (*CPUState) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *CPUState) GetGregs() []uint64 {
	if x != nil {
		return x.Gregs
	}
	return nil
}

func (x *CPUState) GetFpregs() *X64FPRegs {
	if x != nil {
		return x.Fpregs
	}
	return nil
}

type RPCHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType     uint32 `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Status      uint32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	ClientId    string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	PayloadSize uint64 `protobuf:"varint,4,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
}

func (x *RPCHeader) Reset() {
	*x = RPCHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCHeader) ProtoMessage() {}

func (x *RPCHeader) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCHeader.ProtoReflect.Descriptor instead.
func (*RPCHeader) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *RPCHeader) GetMsgType() uint32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *RPCHeader) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RPCHeader) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RPCHeader) GetPayloadSize() uint64 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

type Addr2Sym struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address uint64 `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Addr2Sym) Reset() {
	*x = Addr2Sym{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Addr2Sym) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Addr2Sym) ProtoMessage() {}

func (x *Addr2Sym) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Addr2Sym.ProtoReflect.Descriptor instead.
func (*Addr2Sym) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *Addr2Sym) GetAddress() uint64 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *Addr2Sym) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address         uint64 `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`
	RuntimeRevision uint64 `protobuf:"varint,2,opt,name=runtime_revision,json=runtimeRevision,proto3" json:"runtime_revision,omitempty"`
	ClientRevision  uint64 `protobuf:"varint,3,opt,name=client_revision,json=clientRevision,proto3" json:"client_revision,omitempty"`
	ContentSize     uint32 `protobuf:"varint,4,opt,name=content_size,json=contentSize,proto3" json:"content_size,omitempty"`
	Content         []byte `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *Page) GetAddress() uint64 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *Page) GetRuntimeRevision() uint64 {
	if x != nil {
		return x.RuntimeRevision
	}
	return 0
}

func (x *Page) GetClientRevision() uint64 {
	if x != nil {
		return x.ClientRevision
	}
	return 0
}

func (x *Page) GetContentSize() uint32 {
	if x != nil {
		return x.ContentSize
	}
	return 0
}

func (x *Page) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type LoadLibMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header      *RPCHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	LibraryName string      `protobuf:"bytes,2,opt,name=library_name,json=libraryName,proto3" json:"library_name,omitempty"`
	Addr2Sym    []*Addr2Sym `protobuf:"bytes,3,rep,name=addr2sym,proto3" json:"addr2sym,omitempty"`
}

func (x *LoadLibMsg) Reset() {
	*x = LoadLibMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadLibMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadLibMsg) ProtoMessage() {}

func (x *LoadLibMsg) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadLibMsg.ProtoReflect.Descriptor instead.
func (*LoadLibMsg) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *LoadLibMsg) GetHeader() *RPCHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LoadLibMsg) GetLibraryName() string {
	if x != nil {
		return x.LibraryName
	}
	return ""
}

func (x *LoadLibMsg) GetAddr2Sym() []*Addr2Sym {
	if x != nil {
		return x.Addr2Sym
	}
	return nil
}

type UserContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu         *CPUState `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	StackBottom uint64    `protobuf:"varint,2,opt,name=stack_bottom,json=stackBottom,proto3" json:"stack_bottom,omitempty"`
}

func (x *UserContext) Reset() {
	*x = UserContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContext) ProtoMessage() {}

func (x *UserContext) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserContext.ProtoReflect.Descriptor instead.
func (*UserContext) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *UserContext) GetCpu() *CPUState {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *UserContext) GetStackBottom() uint64 {
	if x != nil {
		return x.StackBottom
	}
	return 0
}

type InvokeFuncMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header       *RPCHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	InvokefuncId uint64       `protobuf:"varint,2,opt,name=invokefunc_id,json=invokefuncId,proto3" json:"invokefunc_id,omitempty"`
	RespId       uint64       `protobuf:"varint,3,opt,name=resp_id,json=respId,proto3" json:"resp_id,omitempty"`
	Ctx          *UserContext `protobuf:"bytes,4,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Page         []*Page      `protobuf:"bytes,5,rep,name=page,proto3" json:"page,omitempty"`
}

func (x *InvokeFuncMsg) Reset() {
	*x = InvokeFuncMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvokeFuncMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeFuncMsg) ProtoMessage() {}

func (x *InvokeFuncMsg) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeFuncMsg.ProtoReflect.Descriptor instead.
func (*InvokeFuncMsg) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

func (x *InvokeFuncMsg) GetHeader() *RPCHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *InvokeFuncMsg) GetInvokefuncId() uint64 {
	if x != nil {
		return x.InvokefuncId
	}
	return 0
}

func (x *InvokeFuncMsg) GetRespId() uint64 {
	if x != nil {
		return x.RespId
	}
	return 0
}

func (x *InvokeFuncMsg) GetCtx() *UserContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *InvokeFuncMsg) GetPage() []*Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type PullPageMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RPCHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Page   []*Page    `protobuf:"bytes,2,rep,name=page,proto3" json:"page,omitempty"`
}

func (x *PullPageMsg) Reset() {
	*x = PullPageMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullPageMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullPageMsg) ProtoMessage() {}

func (x *PullPageMsg) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullPageMsg.ProtoReflect.Descriptor instead.
func (*PullPageMsg) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{10}
}

func (x *PullPageMsg) GetHeader() *RPCHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PullPageMsg) GetPage() []*Page {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x78, 0x36, 0x34, 0x22, 0x65, 0x0a, 0x09, 0x58, 0x36, 0x34, 0x46, 0x50, 0x58, 0x52, 0x65,
	0x67, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x66, 0x69, 0x63, 0x61, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x65, 0x78, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x22, 0x25, 0x0a, 0x09, 0x58,
	0x36, 0x34, 0x58, 0x4d, 0x4d, 0x52, 0x65, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0x88, 0x02, 0x0a, 0x09, 0x58, 0x36, 0x34, 0x46, 0x50, 0x52, 0x65, 0x67, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x63, 0x77, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x63,
	0x77, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x73, 0x77, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x74, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x66, 0x74, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x6f, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x66, 0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x70, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x72, 0x69, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x64,
	0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x72, 0x64, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x78, 0x63, 0x73, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x78, 0x63,
	0x73, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x78, 0x63, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6d, 0x78, 0x63, 0x72, 0x4d, 0x61, 0x73, 0x6b, 0x12,
	0x1e, 0x0a, 0x02, 0x73, 0x74, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x78, 0x36,
	0x34, 0x2e, 0x58, 0x36, 0x34, 0x46, 0x50, 0x58, 0x52, 0x65, 0x67, 0x52, 0x02, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x03, 0x78, 0x6d, 0x6d, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x78,
	0x36, 0x34, 0x2e, 0x58, 0x36, 0x34, 0x58, 0x4d, 0x4d, 0x52, 0x65, 0x67, 0x52, 0x03, 0x78, 0x6d,
	0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x18, 0x0b, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x22, 0x48, 0x0a,
	0x08, 0x43, 0x50, 0x55, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x65,
	0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x05, 0x67, 0x72, 0x65, 0x67, 0x73, 0x12,
	0x26, 0x0a, 0x06, 0x66, 0x70, 0x72, 0x65, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x78, 0x36, 0x34, 0x2e, 0x58, 0x36, 0x34, 0x46, 0x50, 0x52, 0x65, 0x67, 0x73, 0x52,
	0x06, 0x66, 0x70, 0x72, 0x65, 0x67, 0x73, 0x22, 0x7e, 0x0a, 0x09, 0x52, 0x50, 0x43, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x38, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x72, 0x32,
	0x53, 0x79, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0xb1, 0x01, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f,
	0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x27, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x82, 0x01, 0x0a, 0x0a, 0x4c, 0x6f, 0x61, 0x64, 0x4c, 0x69,
	0x62, 0x4d, 0x73, 0x67, 0x12, 0x26, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x78, 0x36, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c,
	0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x29, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x72, 0x32, 0x73, 0x79, 0x6d, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x78, 0x36, 0x34, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x32, 0x53, 0x79, 0x6d,
	0x52, 0x08, 0x61, 0x64, 0x64, 0x72, 0x32, 0x73, 0x79, 0x6d, 0x22, 0x51, 0x0a, 0x0b, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1f, 0x0a, 0x03, 0x63, 0x70, 0x75,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x78, 0x36, 0x34, 0x2e, 0x43, 0x50, 0x55,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74,
	0x61, 0x63, 0x6b, 0x5f, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x42, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x22, 0xb8, 0x01,
	0x0a, 0x0d, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x4d, 0x73, 0x67, 0x12,
	0x26, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x78, 0x36, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x76, 0x6f, 0x6b,
	0x65, 0x66, 0x75, 0x6e, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c,
	0x69, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x66, 0x75, 0x6e, 0x63, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x70, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x03, 0x63, 0x74, 0x78, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x78, 0x36, 0x34, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x52, 0x03, 0x63, 0x74, 0x78, 0x12, 0x1d, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x78, 0x36, 0x34, 0x2e, 0x50, 0x61,
	0x67, 0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x54, 0x0a, 0x0b, 0x50, 0x75, 0x6c, 0x6c,
	0x50, 0x61, 0x67, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x26, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x78, 0x36, 0x34, 0x2e, 0x52, 0x50,
	0x43, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x1d, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x78, 0x36, 0x34, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x32, 0xa5,
	0x01, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x52, 0x50, 0x43, 0x12, 0x2d, 0x0a, 0x07, 0x4c, 0x6f, 0x61,
	0x64, 0x4c, 0x69, 0x62, 0x12, 0x0f, 0x2e, 0x78, 0x36, 0x34, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x4c,
	0x69, 0x62, 0x4d, 0x73, 0x67, 0x1a, 0x0f, 0x2e, 0x78, 0x36, 0x34, 0x2e, 0x4c, 0x6f, 0x61, 0x64,
	0x4c, 0x69, 0x62, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0a, 0x49, 0x6e, 0x76, 0x6f,
	0x6b, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x12, 0x12, 0x2e, 0x78, 0x36, 0x34, 0x2e, 0x49, 0x6e, 0x76,
	0x6f, 0x6b, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x4d, 0x73, 0x67, 0x1a, 0x12, 0x2e, 0x78, 0x36, 0x34,
	0x2e, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x4d, 0x73, 0x67, 0x22, 0x00,
	0x28, 0x01, 0x30, 0x01, 0x12, 0x30, 0x0a, 0x08, 0x50, 0x75, 0x6c, 0x6c, 0x50, 0x61, 0x67, 0x65,
	0x12, 0x10, 0x2e, 0x78, 0x36, 0x34, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x4d,
	0x73, 0x67, 0x1a, 0x10, 0x2e, 0x78, 0x36, 0x34, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x50, 0x61, 0x67,
	0x65, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x69, 0x67, 0x72,
	0x70, 0x63, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x78, 0x36, 0x34,
	0x3b, 0x78, 0x36, 0x34, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData = file_message_proto_rawDesc
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_rawDescData)
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_message_proto_goTypes = []interface{}{
	(*X64FPXReg)(nil),     // 0: x64.X64FPXReg
	(*X64XMMReg)(nil),     // 1: x64.X64XMMReg
	(*X64FPRegs)(nil),     // 2: x64.X64FPRegs
	(*CPUState)(nil),      // 3: x64.CPUState
	(*RPCHeader)(nil),     // 4: x64.RPCHeader
	(*Addr2Sym)(nil),      // 5: x64.Addr2Sym
	(*Page)(nil),          // 6: x64.Page
	(*LoadLibMsg)(nil),    // 7: x64.LoadLibMsg
	(*UserContext)(nil),   // 8: x64.UserContext
	(*InvokeFuncMsg)(nil), // 9: x64.InvokeFuncMsg
	(*PullPageMsg)(nil),   // 10: x64.PullPageMsg
}
var file_message_proto_depIdxs = []int32{
	0,  // 0: x64.X64FPRegs.st:type_name -> x64.X64FPXReg
	1,  // 1: x64.X64FPRegs.xmm:type_name -> x64.X64XMMReg
	2,  // 2: x64.CPUState.fpregs:type_name -> x64.X64FPRegs
	4,  // 3: x64.LoadLibMsg.header:type_name -> x64.RPCHeader
	5,  // 4: x64.LoadLibMsg.addr2sym:type_name -> x64.Addr2Sym
	3,  // 5: x64.UserContext.cpu:type_name -> x64.CPUState
	4,  // 6: x64.InvokeFuncMsg.header:type_name -> x64.RPCHeader
	8,  // 7: x64.InvokeFuncMsg.ctx:type_name -> x64.UserContext
	6,  // 8: x64.InvokeFuncMsg.page:type_name -> x64.Page
	4,  // 9: x64.PullPageMsg.header:type_name -> x64.RPCHeader
	6,  // 10: x64.PullPageMsg.page:type_name -> x64.Page
	7,  // 11: x64.SigRPC.LoadLib:input_type -> x64.LoadLibMsg
	9,  // 12: x64.SigRPC.InvokeFunc:input_type -> x64.InvokeFuncMsg
	10, // 13: x64.SigRPC.PullPage:input_type -> x64.PullPageMsg
	7,  // 14: x64.SigRPC.LoadLib:output_type -> x64.LoadLibMsg
	9,  // 15: x64.SigRPC.InvokeFunc:output_type -> x64.InvokeFuncMsg
	10, // 16: x64.SigRPC.PullPage:output_type -> x64.PullPageMsg
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*X64FPXReg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*X64XMMReg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*X64FPRegs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CPUState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Addr2Sym); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadLibMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvokeFuncMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullPageMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_rawDesc = nil
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
